<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SwipePages.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Behaviors\right.png" />
    <None Remove="Frame.png" />
    <None Remove="Group 7.png" />
    <None Remove="images\right.png" />
    <None Remove="Inter-Regular.ttf" />
    <None Remove="menu.png" />
    <None Remove="menubutton.png" />
    <None Remove="right.png" />
    <None Remove="tripoloski.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Frame.png" />
    <EmbeddedResource Include="fonts\Inter-Regular.ttf" />
    <EmbeddedResource Include="images\right.png" />
    <EmbeddedResource Include="menu.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.Essentials" Version="1.5.1" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="PhoneLog.xaml.cs">
      <DependentUpon>PhoneLog.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="confirm.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="homepage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="register.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
	<ItemGroup>
		<Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="App.xaml.cs">
			<DependentUpon>*.xaml</DependentUpon>
		</Compile>
		<Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="MainPage.xaml.cs">
			<DependentUpon>*.xaml</DependentUpon>
		</Compile>
	</ItemGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Behaviors\right.png" />
    <Resource Include="menu.png" />
    <Resource Include="menubutton.png" />
    <Resource Include="right.png" />
    <Resource Include="SwipePages.cs" />
    <Resource Include="tripoloski.png" />
  </ItemGroup>
  <ItemGroup>
    <None Update="message.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="menubutton.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>